// The continent's towns and the roads joining them to the King's Road, as
// generated by scripts/gen-settlements.ts (src/lib/settlementsData.json).
// Pure lookups shared by the terrain (src/lib/continent.ts, the heartland's
// paths in src/lib/regions.ts), NPCs, shops, inns and the map.

import DATA from "./settlementsData.json";
import type { Region } from "@/types/regions";
import type { SettlementNpcDef, SettlementsData, TownBuildingSlot, TownDecor, TownDef } from "@/types/settlement";

export type { SettlementNpcDef, SettlementsData, TownBuildingSlot, TownDecor, TownDef, TownFamily, TownJob } from "@/types/settlement";

const data = DATA as SettlementsData;
export const TOWNS: readonly TownDef[] = data.towns;
export const SETTLEMENT_NPCS: readonly SettlementNpcDef[] = data.npcs;
export const ROADS: readonly (readonly [number, number][])[] = data.roads;

/** The town whose box holds world tile (tx, ty), if any. */
export function townAt(tx: number, ty: number): TownDef | null {
  for (const t of TOWNS) if (tx >= t.box.tx0 && tx <= t.box.tx1 && ty >= t.box.ty0 && ty <= t.box.ty1) return t;
  return null;
}

/** The towns as named places (region key `town_<key>`). */
export const TOWN_REGIONS: Region[] = TOWNS.map((t) => ({
  key: `town_${t.key}`, name: t.name, ...t.box, label: { tx: t.sq.tx + 12, ty: t.sq.ty - 18 },
}));

/** Road corners (vertices): each road tile and the ones right and below,
 *  so a road is two tiles wide. Built once. */
const ROAD_V: ReadonlySet<string> = (() => {
  const out = new Set<string>();
  for (const road of ROADS) for (const [tx, ty] of road) for (let dy = 0; dy <= 2; dy++) for (let dx = 0; dx <= 2; dx++) out.add(`${tx + dx},${ty + dy}`);
  return out;
})();
export const roadV = (vx: number, vy: number): boolean => ROAD_V.size > 0 && ROAD_V.has(`${vx},${vy}`);
/** Any road corner within `r` corners of (vx, vy). */
export function nearRoad(vx: number, vy: number, r: number): boolean {
  if (ROAD_V.size === 0) return false;
  for (let dy = -r; dy <= r; dy++) for (let dx = -r; dx <= r; dx++) if (ROAD_V.has(`${vx + dx},${vy + dy}`)) return true;
  return false;
}
/** A road tile (any corner on the road). */
export const roadTile = (tx: number, ty: number): boolean => roadV(tx, ty) || roadV(tx + 1, ty) || roadV(tx, ty + 1) || roadV(tx + 1, ty + 1);

// ── The town layout (Hollowmere's, around a square) ─────────────────────
/** Buildings around the square (offsets from its top-left tile). */
export const TOWN_LAYOUT: readonly TownBuildingSlot[] = [
  { suffix: "square", file: "/buildings/town_square.json", kind: "scenery", dx: 0, dy: 0 },
  { suffix: "inn", file: "/buildings/inn.json", kind: "inn", dx: 0, dy: -14 },
  { suffix: "ws", file: "/buildings/waystone.json", kind: "waystone", dx: 14, dy: -4 },
  { suffix: "h1", file: "/buildings/house_1.json", kind: "home", dx: -42, dy: -9 },
  { suffix: "h2", file: "/buildings/cabin_2.json", kind: "home", dx: -28, dy: -9 },
  { suffix: "h3", file: "/buildings/house_2.json", kind: "home", dx: 26, dy: -9 },
  { suffix: "h4", file: "/buildings/cabin_1.json", kind: "home", dx: 40, dy: -9 },
  { suffix: "h5", file: "/buildings/cabin_1.json", kind: "home", dx: -42, dy: 10 },
  { suffix: "h6", file: "/buildings/cabin_2.json", kind: "home", dx: 26, dy: 10 },
];
/** The box a town clears, around its square. */
export const townBox = (sq: { tx: number; ty: number }) => ({ tx0: sq.tx - 50, tx1: sq.tx + 70, ty0: sq.ty - 18, ty1: sq.ty + 30 });
/** Main street rows (through the square's middle), like the King's Road. */
const STREET = { dy0: 6, dy1: 8 };
/** House doors sit at template tile (17, 12); the inn's at (11, 12). */
const HOUSE_DOOR = { dx: 17, dy: 12 };

/** Path corners of a town: main street, door paths, the back lane. */
function townPathCorner(t: TownDef, vx: number, vy: number): boolean {
  const x = vx - t.sq.tx, y = vy - t.sq.ty;
  if (vx >= t.box.tx0 && vx <= t.box.tx1 + 1 && y >= STREET.dy0 && y <= STREET.dy1 + 1) return true;
  for (const b of TOWN_LAYOUT) {
    if (b.kind !== "home") continue;
    const dx = b.dx + HOUSE_DOOR.dx, dy = b.dy + HOUSE_DOOR.dy;
    if (b.dy < 0 && x >= dx && x <= dx + 1 && y >= dy && y <= STREET.dy0) return true; // north houses: door → street
    if (b.dy > 0 && x >= dx && x <= dx + 1 && y >= dy && y <= dy + 2) return true; // south houses: door → lane
  }
  if (y >= 23 && y <= 25 && x >= -26 && x <= 45) return true; // the back lane
  if (x >= 11 && x <= 13 && y >= 14 && y <= 25) return true; // lane → square
  if (x >= 11 && x <= 12 && y >= -2 && y <= 0) return true; // inn door → square
  return false;
}
export function townPathV(vx: number, vy: number): boolean {
  const t = townAt(vx, vy) ?? townAt(vx - 1, vy - 1);
  return !!t && townPathCorner(t, vx, vy);
}

/** Lamps, benches, the statue and the notice board, by tile. */
const DECOR: ReadonlyMap<string, TownDecor> = (() => {
  const out = new Map<string, TownDecor>();
  const set = (tx: number, ty: number, d: TownDecor) => out.set(`${tx},${ty}`, d);
  const tall = (tx: number, ty: number, name: string) => { set(tx, ty - 1, { canopy: `${name}_top` }); set(tx, ty, { lower: `${name}_base` }); };
  for (const t of TOWNS) {
    const { tx: sx, ty: sy } = t.sq;
    tall(sx + 17, sy + 12, "statue");
    // the notice board (bounties), just west of the square below the street
    set(sx - 4, sy + 10, { canopy: "board_tl" }); set(sx - 3, sy + 10, { canopy: "board_tr" });
    set(sx - 4, sy + 11, { lower: "board_bl" }); set(sx - 3, sy + 11, { lower: "board_br" });
    const doors = TOWN_LAYOUT.filter((b) => b.kind === "home" && b.dy < 0).map((b) => sx + b.dx + HOUSE_DOOR.dx);
    for (let tx = t.box.tx0 + 4; tx <= t.box.tx1 - 4; tx += 9) {
      if (tx >= sx - 6 && tx <= sx + 25) continue; // the square and the board
      if (doors.some((d) => Math.abs(tx - d) <= 3)) continue;
      tall(tx, sy + 4, "lamp");
      tall(tx, sy + 11, "lamp");
      set(tx + 1, sy + 11, { lower: "bench_l" }); set(tx + 2, sy + 11, { lower: "bench_r" });
    }
  }
  return out;
})();
export const townDecorAt = (tx: number, ty: number): TownDecor | undefined => (DECOR.size ? DECOR.get(`${tx},${ty}`) : undefined);
